version: '3.3'

services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        deploy:
            restart_policy:
                condition: any
                delay: 3s
                # max_attempts: 3
                window: 30s
        expose:
            - 27017
    
    library:
        image: docker.pkg.github.com/dracoonghost/library/library:1.0
        restart: always
        environment: 
            MONGO_CONNECT_STRING: mongodb://root:example@mongodb:27017/LIBRARY?authSource=admin
        depends_on: 
            - mongodb
        deploy:
            restart_policy:
                condition: any
                delay: 3s
                # max_attempts: 3
                window: 30s
        # command: redis-server --requirepass vDLNktgyMtLBwomm
        ports:
            - '3000:3000'